name: Deploy Next.js App to EC2

on:
  push:
    branches:
      - master # You can change this to your desired branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm install

      - name: Build and export the app
        run: |
          npm run build
          npm run export

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }} # SSH private key for EC2
          EC2_USER: "ubuntu" # Default user for Ubuntu-based EC2
          EC2_HOST: ${{ secrets.EC2_HOST }} # Your EC2 instance's public IP or domain
        run: |
          # Install SSH client
          sudo apt-get install -y openssh-client

          # Add SSH key to SSH agent
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          eval $(ssh-agent -s)
          ssh-add private_key.pem

          # Deploy the static files to EC2
          scp -o StrictHostKeyChecking=no -i private_key.pem -r out/* $EC2_USER@$EC2_HOST:/var/www/wordpress/
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST 'sudo systemctl restart apache2'
